name = "khubs"
type = "javascript"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[build]
command = "npm run build"
cwd = "./"

[build.upload]
format = "service-worker"

[env.production]
# 高創坊 - khubs.net 部署配置
